using System;
using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace Core.DbModels
{
    [Table("homepage_content")]
    public class HomepageContent : BaseModel
    {
        [PrimaryKey("id", false)] // Key is Autogenerated
        public int Id { get; set; }

        [Column("section_name")]
        public string SectionName { get; set; }

        [Column("text_content")]
        public string TextContent { get; set; }

        [Column("last_updated")]
        public DateTime LastUpdated { get; set; }

    }
}